### PR TITLE
Pubsub feature

### PR DESCRIPTION
**Pull request by ILMTitan**
I merged m2_master into my pubsub_feature. I wasn't sure if I should to a PR to pubsub_feature or m2_master first.

### CODE REVIEW

**Comment by Deren-Liao** [comment]
Hi Jim,  Normally, here is the way to check in new features.  Create a feature branch at GoogleCloudPlatform from master ( not  m2_master, We are moving on to master branch now).  Then you create PR from your fork branch to this feature branch.   

The build error says you created some strings in resources but not used. 

CloudExplorerPubSubNoSubscriptionsFoundCaption
PubSubNewTopicWindowHeader
CloudExplorerPubSubListSubscriptionsErrorCaption
CloudExplorerPubSubLoadingSubscriptionsCaption
Found unused strings.

**Comment by iantalarico** [comment]
Was any of this previously reviewed? Or is this all new code?

**Comment by ILMTitan** [comment]
This was previously reviewed, but I had to make some changes to the xaml to
work with other changes.

**Comment by iantalarico** [comment]
Can you just point out the files with changes so we can review them? I'd rather no re-review 2000 lines of code :)

**Pull request closed without merging**
