### PR TITLE
Reverting out to ref.

### PR DESCRIPTION
**Pull request by ivannaranjo**
The parameter to the `SetValueAndRaise()` method is a **ref** parameter. We are passing the _pointer_ to the variable. The method does **not** produce a value into its parameter. We need to use the right semantics for C# here.

I have reverted the change, and I am ashamed to say that I didn't see this on the review. I will be more careful in the future.

### CODE REVIEW

**Comment by ILMTitan** [comment]
When this parameter is a ref, resharper gives the warning [Redundant Assignment](https://www.jetbrains.com/help/resharper/2017.1/RedundantAssignment.html).

Because the initial value is never read, it is in essence producing a value. `out` restricts the implementation; the implementation must the parameter as uninitialized and requires an assignment before the method returns. Our method meets both of those criteria. In return `out` provides extra functionality to callers (sending uninitialized varaibles etc.).

Why would we forego the extra functionality when our implementation meets the criteria?

**Comment by ivannaranjo** [comment]
Because `out` is used for methods that _return_ something on them. This is not what the `SetValueAndRaise` does, it does not return anything. The method is given the storage where to store the value, that's it.

I don't care what Resharper is saying, `out` is not the right annotation for this.

**Comment by ivannaranjo** [comment]
I suggest you turn off that warning on Resharper for the `SetValueAndRaise()` method, since it clearly is not getting it right.

**Comment by ivannaranjo** [comment]
Updated to fix the conflicts. PTAL.

**Comment by ivannaranjo** [comment]
Thank you.

**Pull request merged**
